name: wiki-private

services:

  # This compose file relies on a properly configured ".env" file
  # Make a copy of .env.sample to configure your environment

  db:
    image: postgres:16-alpine
    container_name: wiki-private-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #logging:
    #  driver: "none"
    restart: always
    volumes:
      - wikijs-private-db:/var/lib/postgresql/data
    # -------------------------------------------------------------------------------
    # Uncomment this section to expose mysql to connections outside of the container
    # such as MySQL Workbench
    # -------------------------------------------------------------------------------
    # ports:
    #  - ${POSTGRES_EXTERNAL_PORT}:5432

  app:
    image: ghcr.io/requarks/wiki:${WIKIJS_VERSION_TAG}
    container_name: wiki-private-app
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DATABASE}
    restart: unless-stopped
    ports:
      - "${WIKIJS_EXTERNAL_PORT}:3000"
    volumes:
      - wikijs-private-content:/wiki/data/content

volumes:
  wikijs-private-db:
    name: wikijs-private-db
  wikijs-private-content:
    name: wikijs-private-content